apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
  - path: patch-argocd-server-debug.yaml
    target:
      group: apps
      kind: Deployment
      labelSelector: "app.kubernetes.io/name=argocd-server"
  - path: patch-argocd-config.yaml
