apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system
resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.28.0/controller.yaml

patches:
  - path: patch-disable-key-renew-period.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: sealed-secrets-controller
