apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd
  source:
    path: deployment-repository/services/argocd
    repoURL: https://github.com/chdalski/argocd-test
    targetRevision: HEAD
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: guestbook
#   namespace: argocd
# spec:
#   destination:
#     namespace: guestbook
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     path: deployment-repository/services/guestbook
#     repoURL: https://github.com/chdalski/argocd-test
#     targetRevision: HEAD
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
